var verbsSpanish = [
    { spanish: "preguntar", english: "ask", slovak: "spýtať sa" },
    { spanish: "ser", english: "be", slovak: "byť" },
    { spanish: "traer", english: "bring", slovak: "priniesť" },
    { spanish: "comprar", english: "buy", slovak: "kúpiť" },
    { spanish: "llamar", english: "call", slovak: "volať" },
    { spanish: "poder", english: "can", slovak: "môcť" },
    { spanish: "elegir", english: "choose", slovak: "vybrať" },
    { spanish: "venir", english: "come", slovak: "prísť" },
    { spanish: "hacer", english: "do", slovak: "robiť" },
    { spanish: "beber", english: "drink", slovak: "piť" },
    { spanish: "comer", english: "eat", slovak: "jesť" },
    { spanish: "sentir", english: "feel", slovak: "cítiť" },
    { spanish: "encontrar", english: "find", slovak: "nájsť" },
    { spanish: "conseguir", english: "get", slovak: "získať" },
    { spanish: "dar", english: "give", slovak: "dať" },
    { spanish: "ir", english: "go", slovak: "ísť" },
    { spanish: "tener", english: "have", slovak: "mať" },
    { spanish: "oír", english: "hear", slovak: "počuť" },
    { spanish: "ayudar", english: "help", slovak: "pomôcť" },
    { spanish: "saber", english: "know", slovak: "vedieť" },
    { spanish: "aprender", english: "learn", slovak: "učiť sa" },
    { spanish: "gustar", english: "like", slovak: "páčiť sa" },
    { spanish: "escuchar", english: "listen", slovak: "počúvať" },
    { spanish: "vivir", english: "live", slovak: "žiť" },
    { spanish: "mirar", english: "look", slovak: "pozerať" },
    { spanish: "hacer", english: "make", slovak: "robiť" },
    { spanish: "necesitar", english: "need", slovak: "potrebovať" },
    { spanish: "pagar", english: "pay", slovak: "platiť" },
    { spanish: "jugar", english: "play", slovak: "hrať" },
    { spanish: "poner", english: "put", slovak: "položiť" },
    { spanish: "leer", english: "read", slovak: "čítať" },
    { spanish: "decir", english: "say", slovak: "povedať" },
    { spanish: "ver", english: "see", slovak: "vidieť" },
    { spanish: "enviar", english: "send", slovak: "poslať" },
    { spanish: "mostrar", english: "show", slovak: "ukázať" },
    { spanish: "dormir", english: "sleep", slovak: "spať" },
    { spanish: "empezar", english: "start", slovak: "začať" },
    { spanish: "quedarse", english: "stay", slovak: "zostať" },
    { spanish: "tomar", english: "take", slovak: "zobrať" },
    { spanish: "hablar", english: "talk", slovak: "hovoriť" },
    { spanish: "contar", english: "tell", slovak: "povedať" },
    { spanish: "pensar", english: "think", slovak: "myslieť" },
    { spanish: "intentar", english: "try", slovak: "pokúsiť sa" },
    { spanish: "usar", english: "use", slovak: "použiť" },
    { spanish: "caminar", english: "walk", slovak: "chodiť" },
    { spanish: "querer", english: "want", slovak: "chcieť" },
    { spanish: "ver", english: "watch", slovak: "pozerať" },
    { spanish: "trabajar", english: "work", slovak: "pracovať" },
    { spanish: "escribir", english: "write", slovak: "písať" }
];

var verbsGerman = [
    { german: "fragen", english: "ask", slovak: "spýtať sa" },
    { german: "sein", english: "be", slovak: "byť" },
    { german: "bringen", english: "bring", slovak: "priniesť" },
    { german: "kaufen", english: "buy", slovak: "kúpiť" },
    { german: "rufen", english: "call", slovak: "volať" },
    { german: "können", english: "can", slovak: "môcť" },
    { german: "wählen", english: "choose", slovak: "vybrať" },
    { german: "kommen", english: "come", slovak: "prísť" },
    { german: "machen", english: "do", slovak: "robiť" },
    { german: "trinken", english: "drink", slovak: "piť" },
    { german: "essen", english: "eat", slovak: "jesť" },
    { german: "fühlen", english: "feel", slovak: "cítiť" },
    { german: "finden", english: "find", slovak: "nájsť" },
    { german: "bekommen", english: "get", slovak: "získať" },
    { german: "geben", english: "give", slovak: "dať" },
    { german: "gehen", english: "go", slovak: "ísť" },
    { german: "haben", english: "have", slovak: "mať" },
    { german: "hören", english: "hear", slovak: "počuť" },
    { german: "helfen", english: "help", slovak: "pomôcť" },
    { german: "wissen", english: "know", slovak: "vedieť" },
    { german: "lernen", english: "learn", slovak: "učiť sa" },
    { german: "mögen", english: "like", slovak: "páčiť sa" },
    { german: "hören", english: "listen", slovak: "počúvať" },
    { german: "leben", english: "live", slovak: "žiť" },
    { german: "schauen", english: "look", slovak: "pozerať" },
    { german: "machen", english: "make", slovak: "robiť" },
    { german: "brauchen", english: "need", slovak: "potrebovať" },
    { german: "bezahlen", english: "pay", slovak: "platiť" },
    { german: "spielen", english: "play", slovak: "hrať" },
    { german: "legen", english: "put", slovak: "položiť" },
    { german: "lesen", english: "read", slovak: "čítať" },
    { german: "sagen", english: "say", slovak: "povedať" },
    { german: "sehen", english: "see", slovak: "vidieť" },
    { german: "senden", english: "send", slovak: "poslať" },
    { german: "zeigen", english: "show", slovak: "ukázať" },
    { german: "schlafen", english: "sleep", slovak: "spať" },
    { german: "anfangen", english: "start", slovak: "začať" },
    { german: "bleiben", english: "stay", slovak: "zostať" },
    { german: "nehmen", english: "take", slovak: "zobrať" },
    { german: "sprechen", english: "talk", slovak: "hovoriť" },
    { german: "erzählen", english: "tell", slovak: "povedať" },
    { german: "denken", english: "think", slovak: "myslieť" },
    { german: "versuchen", english: "try", slovak: "pokúsiť sa" },
    { german: "benutzen", english: "use", slovak: "použiť" },
    { german: "gehen", english: "walk", slovak: "chodiť" },
    { german: "wollen", english: "want", slovak: "chcieť" },
    { german: "sehen", english: "watch", slovak: "pozerať" },
    { german: "arbeiten", english: "work", slovak: "pracovať" },
    { german: "schreiben", english: "write", slovak: "písať" }
];

var verbsRussian = [
    { russian: "спрашивать", english: "ask", slovak: "spýtať sa" },
    { russian: "быть", english: "be", slovak: "byť" },
    { russian: "становиться", english: "become", slovak: "stať sa" },
    { russian: "приносить", english: "bring", slovak: "priniesť" },
    { russian: "покупать", english: "buy", slovak: "kúpiť" },
    { russian: "звонить", english: "call", slovak: "volať" },
    { russian: "мочь", english: "can", slovak: "môcť" },
    { russian: "выбирать", english: "choose", slovak: "vybrať" },
    { russian: "приходить", english: "come", slovak: "prísť" },
    { russian: "делать", english: "do", slovak: "robiť" },
    { russian: "пить", english: "drink", slovak: "piť" },
    { russian: "есть", english: "eat", slovak: "jesť" },
    { russian: "чувствовать", english: "feel", slovak: "cítiť" },
    { russian: "находить", english: "find", slovak: "nájsť" },
    { russian: "получать", english: "get", slovak: "získať" },
    { russian: "давать", english: "give", slovak: "dať" },
    { russian: "идти", english: "go", slovak: "ísť" },
    { russian: "иметь", english: "have", slovak: "mať" },
    { russian: "слышать", english: "hear", slovak: "počuť" },
    { russian: "помогать", english: "help", slovak: "pomôcť" },
    { russian: "знать", english: "know", slovak: "vedieť" },
    { russian: "учить", english: "learn", slovak: "učiť sa" },
    { russian: "любить", english: "like", slovak: "páčiť sa" },
    { russian: "слушать", english: "listen", slovak: "počúvať" },
    { russian: "жить", english: "live", slovak: "žiť" },
    { russian: "смотреть", english: "look", slovak: "pozerať" },
    { russian: "делать", english: "make", slovak: "robiť" },
    { russian: "нуждаться", english: "need", slovak: "potrebovať" },
    { russian: "платить", english: "pay", slovak: "platiť" },
    { russian: "играть", english: "play", slovak: "hrať" },
    { russian: "класть", english: "put", slovak: "položiť" },
    { russian: "читать", english: "read", slovak: "čítať" },
    { russian: "говорить", english: "say", slovak: "povedať" },
    { russian: "видеть", english: "see", slovak: "vidieť" },
    { russian: "отправлять", english: "send", slovak: "poslať" },
    { russian: "показывать", english: "show", slovak: "ukázať" },
    { russian: "спать", english: "sleep", slovak: "spať" },
    { russian: "начинать", english: "start", slovak: "začať" },
    { russian: "оставаться", english: "stay", slovak: "zostať" },
    { russian: "брать", english: "take", slovak: "zobrať" },
    { russian: "говорить", english: "talk", slovak: "hovoriť" },
    { russian: "рассказывать", english: "tell", slovak: "povedať" },
    { russian: "думать", english: "think", slovak: "myslieť" },
    { russian: "пытаться", english: "try", slovak: "pokúsiť sa" },
    { russian: "использовать", english: "use", slovak: "použiť" },
    { russian: "ходить", english: "walk", slovak: "chodiť" },
    { russian: "хотеть", english: "want", slovak: "chcieť" },
    { russian: "смотреть", english: "watch", slovak: "pozerať" },
    { russian: "работать", english: "work", slovak: "pracovať" },
    { russian: "писать", english: "write", slovak: "písať" }
];

var verbsJapanese = [
    { japanese: "聞く (きく)", english: "ask", slovak: "spýtať sa" },
    { japanese: "ある / いる", english: "be", slovak: "byť" },
    { japanese: "持ってくる (もってくる)", english: "bring", slovak: "priniesť" },
    { japanese: "買う (かう)", english: "buy", slovak: "kúpiť" },
    { japanese: "呼ぶ (よぶ)", english: "call", slovak: "volať" },
    { japanese: "できる", english: "can", slovak: "môcť" },
    { japanese: "選ぶ (えらぶ)", english: "choose", slovak: "vybrať" },
    { japanese: "来る (くる)", english: "come", slovak: "prísť" },
    { japanese: "する", english: "do", slovak: "robiť" },
    { japanese: "飲む (のむ)", english: "drink", slovak: "piť" },
    { japanese: "食べる (たべる)", english: "eat", slovak: "jesť" },
    { japanese: "感じる (かんじる)", english: "feel", slovak: "cítiť" },
    { japanese: "見つける (みつける)", english: "find", slovak: "nájsť" },
    { japanese: "得る (える)", english: "get", slovak: "získať" },
    { japanese: "与える (あたえる)", english: "give", slovak: "dať" },
    { japanese: "行く (いく)", english: "go", slovak: "ísť" },
    { japanese: "持つ (もつ)", english: "have", slovak: "mať" },
    { japanese: "聞こえる (きこえる)", english: "hear", slovak: "počuť" },
    { japanese: "助ける (たすける)", english: "help", slovak: "pomôcť" },
    { japanese: "知る (しる)", english: "know", slovak: "vedieť" },
    { japanese: "学ぶ (まなぶ)", english: "learn", slovak: "učiť sa" },
    { japanese: "好き (すき)", english: "like", slovak: "páčiť sa" },
    { japanese: "聞く (きく)", english: "listen", slovak: "počúvať" },
    { japanese: "住む (すむ)", english: "live", slovak: "žiť" },
    { japanese: "見る (みる)", english: "look", slovak: "pozerať" },
    { japanese: "作る (つくる)", english: "make", slovak: "robiť" },
    { japanese: "必要とする (ひつようとする)", english: "need", slovak: "potrebovať" },
    { japanese: "払う (はらう)", english: "pay", slovak: "platiť" },
    { japanese: "遊ぶ (あそぶ)", english: "play", slovak: "hrať" },
    { japanese: "置く (おく)", english: "put", slovak: "položiť" },
    { japanese: "読む (よむ)", english: "read", slovak: "čítať" },
    { japanese: "言う (いう)", english: "say", slovak: "povedať" },
    { japanese: "見る (みる)", english: "see", slovak: "vidieť" },
    { japanese: "送る (おくる)", english: "send", slovak: "poslať" },
    { japanese: "見せる (みせる)", english: "show", slovak: "ukázať" },
    { japanese: "寝る (ねる)", english: "sleep", slovak: "spať" },
    { japanese: "始める (はじめる)", english: "start", slovak: "začať" },
    { japanese: "滞在する (たいざいする)", english: "stay", slovak: "zostať" },
    { japanese: "取る (とる)", english: "take", slovak: "zobrať" },
    { japanese: "話す (はなす)", english: "talk", slovak: "hovoriť" },
    { japanese: "言う (いう)", english: "tell", slovak: "povedať" },
    { japanese: "思う (おもう)", english: "think", slovak: "myslieť" },
    { japanese: "試みる (こころみる)", english: "try", slovak: "pokúsiť sa" },
    { japanese: "使う (つかう)", english: "use", slovak: "použiť" },
    { japanese: "歩く (あるく)", english: "walk", slovak: "chodiť" },
    { japanese: "欲しい (ほしい)", english: "want", slovak: "chcieť" },
    { japanese: "見る (みる)", english: "watch", slovak: "pozerať" },
    { japanese: "働く (はたらく)", english: "work", slovak: "pracovať" },
    { japanese: "書く (かく)", english: "write", slovak: "písať" }
];

export { verbsSpanish, verbsGerman, verbsRussian, verbsJapanese };